### ISSUE TITLE
TODO in the rest of days

### ISSUE THREAD

**Issue by JunmingZhang** [dcsil/jerryrat#263]
491 TODO

- [x] The short write up should be adequately long enough to tell us what to expect and highlight what you think is important.
- [x] Code coverage
- [x] logging system on Heroku
- [x] once finished, deploy on Heroku
- [x] quality check
